### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by philfreo** [Codecademy/backbone.declarative#6]
Any interest in publishing to npm?

**Comment by amasad** [comment]
I don't see why not. Maybe Codecademy can give you commit access /cc @jakemhiller

**Comment by jakemhiller** [comment]
@philfreo happy to give you access if you want it!

**Comment by philfreo** [comment]
Sure. And then just let me know your npm usernames so I can add you as collaborators.

**Comment by philfreo** [comment]
Bump :)

**Comment by jakemhiller** [comment]
@philfreo you should have commit access, you can add the NPM user `codecademy` when you publish it.

Let me know if you need anything else, and thanks!

**Comment by philfreo** [comment]
Thanks. Done! https://www.npmjs.com/package/backbone.declarative
